export const routes = {
  home: "/Chess_Academy/",
  contactUs: "/Chess_Academy/contact-us",
  aboutUs: "/Chess_Academy/about-us",
  faq: "/Chess_Academy/faq",
  training: "/Chess_Academy/training",
  fairPlay: "/Chess_Academy/fair-play",
  login: "/Chess_Academy/login",
  register: "/Chess_Academy/register",
  courses: "/Chess_Academy/courses",
  ourcouch: "/Chess_Academy/ourcouch",
  privateLesson: "/Chess_Academy/private-lesson",
  ranksAndBadges: "/Chess_Academy/ranks-and-badges",
  puzzles: "/Chess_Academy/puzzles/:level",
  chooseDifficulty: "/Chess_Academy/puzzles/choose-difficulty",
  playVsComputer: "/Chess_Academy/play/computer/:level",
  chooseComputerLevel: "/Chess_Academy/play/choose-computer-level",
  dailyPuzzle: "/Chess_Academy/daily-chess-puzzle",
  vision: "/Chess_Academy/vision",
};
