export const routes = {
  home: "/",
  contactUs: "/contact-us",
  aboutUs: "/about-us",
  faq: "/faq",
  training: "/training",
  fairPlay: "/fair-play",
  login: "/login",
  register: "/register",
  courses: "courses",
  ourcouch: "/ourcouch",
  ourcoach: "/ourcoach",
  privateLesson: "/private-lesson",
  ranksAndBadges: "/ranks-and-badges",
  playVsComputer: "/play/computer/:level",
  chooseComputerLevel: "/play/choose-computer-level",
  puzzles: "/puzzles",
  pawnsGame: "/pawns-game",
};
